#pragma once

enum TextureID
{
	SOLDIER			= 1,
	YELLOW_MONSTER	= 2,
	RED_MONSTER		= 3,
	BLUE_MONSTER	= 4,
	SETTLEMENT		= 5,
	DEFAULT_BULLET	= 6,
	HEALTH_PACK		= 7,
	HEALTH_BAR		= 8,
	ARMOR			= 9,
	HASTE			= 10,
	LAZER_BULLET	= 11,
	LAZER_PICKUP	= 12,
};

enum LevelID
{
	START_MENU	 = 1,
	BATTLEGROUND = 2,
};

enum MonsterAIType
{
	NO_TYPE			  = 0,
	AI_YELLOW_MONSTER = 1,
	AI_RED_MONSTER	  = 2,
	AI_BLUE_MONSTER	  = 3,
};

enum MonsterAIState
{
	NO_STATE	= 0,
	CHOOSE	= 1,
	SEEK	= 2,
	ATTACK	= 3,
};

enum AudioClipID
{
	BATTLE_MUSIC_CLIP = 1,
	MONSTER_DAMAGE_CLIP,
	MONSTER_DIE_CLIP,
	MONSTER_SPAWN_CLIP,
	MONSTER_WALK_CLIP,
	PLAYER_DAMAGE_CLIP,
	PLAYER_DIE_CLIP,
	PLAYER_DEFAULT_FIRE_CLIP,
	PLAYER_WALK_CLIP,
	SETTLEMENT_DAMAGE_CLIP,
	SETTLEMENT_DIE_CLIP,
};

enum AudioSourceID
{
	BACKGROUND_MUSIC_SOURCE	= 1,
	MONSTER_DAMAGE_SOURCE,
	MONSTER_SPAWN_SOURCE,
	MONSTER_WALK_SOURCE,
	SETTLEMENT_DAMAGE_SOURCE,
	SETTLEMENT_DEATH_SOURCE,
};